# Generated by Django 2.2.8 on 2020-08-31 19:50

from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modela',
            name='custom_field',
            field=testapp.models.CustomField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ'),
        ),
        migrations.AddField(
            model_name='modelb',
            name='custom_field',
            field=testapp.models.CustomField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ'),
        ),
        migrations.AddField(
            model_name='modelc',
            name='custom_field',
            field=testapp.models.CustomField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ'),
        ),
        migrations.AddField(
            model_name='modeld',
            name='custom_field',
            field=testapp.models.CustomField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ'),
        ),
        migrations.AlterField(
            model_name='modela',
            name='char_field',
            field=models.CharField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ', max_length=255),
        ),
        migrations.AlterField(
            model_name='modela',
            name='text_field',
            field=models.TextField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ"'),
        ),
        migrations.AlterField(
            model_name='modelb',
            name='char_field',
            field=models.CharField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ', max_length=255),
        ),
        migrations.AlterField(
            model_name='modelb',
            name='text_field',
            field=models.TextField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ"'),
        ),
        migrations.AlterField(
            model_name='modelc',
            name='char_field',
            field=models.CharField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ', max_length=255),
        ),
        migrations.AlterField(
            model_name='modelc',
            name='text_field',
            field=models.TextField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ"'),
        ),
        migrations.AlterField(
            model_name='modeld',
            name='char_field',
            field=models.CharField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ', max_length=255),
        ),
        migrations.AlterField(
            model_name='modeld',
            name='text_field',
            field=models.TextField(default='ℋ ℌ ℍ,ℎ;ℏ ℐ ℑ ℒ ℓ"'),
        ),
    ]
