# Generated by Django 2.2.5 on 2020-07-29 08:42

from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeld',
            name='my_field',
            field=testapp.models.MyField(blank=True, null=True),
        ),
    ]
