# Generated by Django 2.2.10 on 2022-08-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200831_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelb',
            options={'verbose_name': 'ModelB'},
        ),
        migrations.AlterModelOptions(
            name='modelc',
            options={'verbose_name': 'ModelC'},
        ),
        migrations.AlterModelOptions(
            name='modeld',
            options={'verbose_name': 'ModelD'},
        ),
        migrations.CreateModel(
            name='Issue6Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.ModelA')),
                ('model_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.ModelB')),
            ],
            options={
                'verbose_name': 'Issue6Model',
            },
        ),
    ]
