# Generated by Django 4.2 on 2026-01-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200831_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelb',
            options={'verbose_name': 'ModelB'},
        ),
        migrations.AlterModelOptions(
            name='modelc',
            options={'verbose_name': 'ModelC'},
        ),
        migrations.AlterModelOptions(
            name='modeld',
            options={'verbose_name': 'ModelD'},
        ),
        migrations.AddField(
            model_name='modelc',
            name='model_dd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_c_dd', to='testapp.modeld'),
        ),
    ]
